---
- name: Create temporary directory to store kubeconfig
  become: true
  ansible.builtin.tempfile:
    suffix: .kubeconfig
    state: directory
  register: kubeconfig_dir

- name: Create admin kubeconfig
  become: true
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - phase
      - kubeconfig
      - admin
      - "--kubeconfig-dir={{ kubeconfig_dir.path }}"
      - "--control-plane-endpoint={{ kubeadm_control_plane_endpoint }}"
  changed_when: true

- name: Download kubeconfig
  become: true
  ansible.builtin.fetch:
    src: "{{ kubeconfig_dir.path }}/admin.conf"
    dest: "{{ kubeadm_local_kubeconfig_path }}"
    flat: true

- name: Ensure local kubeconfig has safe permissions
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ kubeadm_local_kubeconfig_path }}"
    mode: "u=rw,g=,o="

- name: Delete remote kubeconfig
  become: true
  ansible.builtin.file:
    path: "{{ kubeconfig_dir.path }}"
    state: absent
