---
- name: Deployment
  delegate_to: localhost
  run_once: true
  block:
    - name: Ensure Helm repository is available
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/
        state: present

    - name: Ensure Cilium is deployed
      kubernetes.core.helm:
        name: cilium
        namespace: kube-system
        chart_ref: cilium/cilium
        chart_version: "{{ cilium_version }}"
        release_values:
          encryption:
            enabled: true
            type: wireguard
          l7Proxy: false
          ipam:
            operator:
              clusterPoolIPv4PodCIDRList:
                - "{{ cilium_pod_cidr }}"
          hubble:
            relay:
              enabled: true
            ui:
              enabled: true
          prometheus:
            enabled: true
            port: 9089
          operator:
            prometheus:
              enabled: true
        state: present
