---
# https://docs.cilium.io/en/stable/operations/system_requirements/#firewall-rules

- name: Ensure VXLAN overlay is allowed through firewall
  become: true
  community.general.ufw:
    rule: allow
    port: 8472
    proto: udp
    comment: Cilium - VXLAN overlay

- name: Ensure Cilium health checks are allowed through firewall
  become: true
  community.general.ufw:
    rule: allow
    port: 4240
    proto: tcp
    comment: Cilium - health checks

- name: Ensure Hubble components are allowed through firewall
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    comment: Cilium - Hubble
  loop:
    - 4244
    - 4245

- name: Ensure WireGuard is allowed through firewall
  become: true
  community.general.ufw:
    rule: allow
    port: 51871
    proto: udp
    comment: Cilium - WireGuard
