---
galaxy_info:
  author: dannixon
  description: Installs kubeadm prerequisites and performs kubeadm operations.
  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
        - focal

dependencies: []
