---
- name: Single server installation
  ansible.builtin.debug:
    var: k3s_single_server

- name: High availability installation
  ansible.builtin.debug:
    var: k3s_ha_install

- name: Ensure K8s API is allowed through firewall
  become: true
  community.general.ufw:
    rule: allow
    port: 6443
    proto: tcp
    comment: k3s - K8s API

- name: Ensure Kubelet metrics is allowed through firewall
  become: true
  community.general.ufw:
    rule: allow
    port: 10250
    proto: tcp
    comment: k3s - kublet metrics

- name: Ensure etcd is allowed through firewall
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    comment: k3s - etcd
  loop:
    - 2379
    - 2380
  when: inventory_hostname in groups['k3s_servers'] and k3s_ha_install

- name: Enable IPv4 forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Download K3s binary
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    checksum: "sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "u=rx,g=rx,o=rx"

- name: Ensure k3s-killall script is present
  become: true
  ansible.builtin.template:
    src: k3s-killall.sh
    dest: /usr/local/bin/k3s-killall.sh
    owner: root
    group: root
    mode: "u=rx,g=rx,o=rx"
