---
k3s_ha_install: "{{ groups['k3s_servers'] | length > 1 }}"

k3s_server_location: /var/lib/rancher/k3s

k3s_server_host: "{{ hostvars[groups['k3s_servers'][0]]['ansible_host'] }}"
k3s_tokens: "{{ hostvars[groups['k3s_servers'][0]]['tokens'] }}"
